Update eshoponweb-cicd.yml

diff --git a/.github/workflows/eshoponweb-cicd.yml b/.github/workflows/eshoponweb-cicd.yml
--- a/.github/workflows/eshoponweb-cicd.yml
+++ b/.github/workflows/eshoponweb-cicd.yml
@@ -16,6 +16,10 @@ jobs:
   # Build and test
   buildandtest:
     runs-on: ubuntu-latest
+    outputs:
+      test_results: ${{ steps.unittestoutput.outputs.test_results }}
+      test_outcome: ${{ steps.unittestoutput.outputs.test_outcome }}
+      
     steps:
     - uses: actions/checkout@v2
 
@@ -29,8 +33,50 @@ jobs:
       run: dotnet build ./eShopOnWeb.sln --configuration Release
       
     - name: Test with dotnet
-      run: dotnet test ./eShopOnWeb.sln --configuration Release
-      
+      id: unittest
+      run: |
+        dotnet test ./eShopOnWeb.sln --configuration Release |& tee test_results.txt
+        
+        # break if 'dotnet test' failed
+        test ${PIPESTATUS[0]} -eq 0
+        continue-on-error: true
+
+    # Create string output
+    - name: Create output from tests
+      run: |
+        RESULT=$(cat test_results.txt)
+        echo "## Unit Tests Output" >> result.string
+        echo "<details><summary>Click to view unit tests output</summary>" >> result.string
+        echo "" >> result.string
+        echo '```' >> result.string
+        echo "$RESULT" >> result.string
+        echo '```' >> result.string
+        echo "</details>" >> result.string
+          
+        SUMMARY=$(cat result.string)
+        SUMMARY="${SUMMARY//'%'/'%25'}"
+        SUMMARY="${SUMMARY//$'\n'/'%0A'}"
+        SUMMARY="${SUMMARY//$'\r'/'%0D'}"
+          
+        echo "::set-output name=summary::$SUMMARY"
+
+    - name: "Transform Unit Tests output"
+      id: unittestoutput
+      if: steps.unittest.outcome == 'failure'
+      run: |
+        test_results=$(cat test_results.txt)
+        test_results="${test_results//'%'/'%25'}"
+        test_results="${test_results//$'\n'/'%0A'}"
+        test_results="${test_results//$'\r'/'%0D'}"
+
+        echo "::set-output name=test_results::${test_results}"
+        echo "::set-output name=test_outcome::${{ steps.unittest.outcome }}"
+
+    # Publish to task summary
+    - name: Publish to Task Summary
+      run: |
+        cat result.string >> $GITHUB_STEP_SUMMARY
+
     - name: dotnet publish
       run: dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
       
